### ISSUE TITLE
When a variable is in a `GRAPH` clause, the bound variables are not used

### ISSUE THREAD

**Issue by dwhitney** [Callidon/sparql-engine#16]
*NOTE* I have fixed this bug in my fork, but there is a failing test I need to resolve and I have only fixed this for `GRAPH` clauses. This also needs to work in `SERVICE` clauses. I will submit a PR when that work is done.

**Describe the bug**

If you check section 13.3.3 (Restricting Possible GraphIRIs)[https://www.w3.org/TR/sparql11-query/#GraphPattern] it describes and shows an example where a variable is used in a graph clause, like `GRAPH ?ppd`, where `?ppd` is a bound variable. This example won't work in sparql-engine since only named and default graphs are checked for variables.

**To Reproduce**

You can load the data and query from the example mentioned above.

**Expected behavior**

The results described in the section should be produced

**Comment by dwhitney** [comment]
Hey just an update on this...

While tracking down some performance issues I found a better solve for this. The latest version of SPARQL.js has changed the AST a bit for the `GRAPH` and `SERVICE` clause to tell you whether or not it's a variable or value. When I get a moment I'll upgrade SPARQL.js and make the appropriate modifications. This will be better than the current PR.

**Comment by JuniperChicago** [comment]
@Callidon @dwhitney Some weeks ago, when I was working on my fork of this library, I caught some errors in SPARQL.js and it was updated. This change also affects some of the typings defined in this library. I have made these changes in my fork but cannot get the time to post... I just wanted to point out they were there.

**Comment by dwhitney** [comment]
yeah I noticed the SPARQL.js tests aren't passing :/

**Comment by dwhitney** [comment]
I thought this worked, but it doesn't. I've added support for 0.5.3, and I'll make a PR after adding some tests.
