### ISSUE TITLE
Aggregates

### ISSUE THREAD

**Issue by dwhitney** [Callidon/sparql-engine#29]
Do aggregates actually work? I have tested them out and they don't seem to really do what's advertised. If this is not a known issue, I can provide some examples, but otherwise, are there plans to build this in?

TIA!

**Comment by Callidon** [comment]
Hi
Aggregates do work, but they require to add a `GROUP BY` clause to the query. Otherwise, the framework will not return correct results.

So, for example, If you want to count all distinct subjects in a RDF dataset, you can use the following query:
```
SELECT (COUNT(DISTINCT ?s) AS ?c)
WHERE {
  ?s ?p ?o
}
GROUP BY ?s
```

**Comment by Callidon** [comment]
Well, I've just pushed some modifications on the `master` branch that should allow SPARQL aggregates to work **without** adding a GROUP BY clause. 

I will be glad if you could try it and provide some feedback.

**Comment by dwhitney** [comment]
Really appreciate it! I will check it out and provide feedback

**Comment by dwhitney** [comment]
AWESOME! I will try it out some time this week. Thanks!

**Comment by dwhitney** [comment]
oh ha - old comment :)
