### ISSUE TITLE
Abstract return type from find?

### ISSUE THREAD

**Issue by dwhitney** [Callidon/sparql-engine#3]
Hey I've been using this the last few weeks and I really love it! I'm wondering how you'd feel about making the return type from "find" on the graph function more abstract.  I'd rather not have to add the dependency of asynciterator to my project and if there were just some class or interface to make sure I returned from "find" then I wouldn't have to. Thoughts?

**Comment by Callidon** [comment]
Hi

A bit of context first. All the architecture follows the pipeline paradigm, popularized by database systems. I use it here because it avoids a lot of data materialization and allows to read solutions in a stream (either in a pull or push fashion). Currently, I use the `asynciterator` package because it provides so many useful primitives to work with the paradigm.

However, I agree with you that I should not require users to use specifically `asynciterator` to implements a subclass of `Graph`. I have an idea to solve this: `asynciterator` can also be used with [Node.js Streams](https://nodejs.org/api/stream.html). Do you think that making methods `Graph.find` and `Graph.evalBGP` returns a `Readable` Stream could solve this?

**Comment by dwhitney** [comment]
an interface compatible with `Readable` Stream would be great!

**Comment by dwhitney** [comment]
Hey I tried it out and it works pretty well. I noticed that you still require AsyncIterator on `evalBGP`? Is that going to change?

**Comment by Callidon** [comment]
Thank you, nice to hear that it works :) About `evalBGP`, I don't see what could prevent me to change the API to return a `Readable` as well. I will investigate it.

While I'm on it, di you have any other API suggestion in mind ?

**Comment by Callidon** [comment]
Okay, I changed the `Graph.evalBGP` API in d72d46d491db0c4b739146b9d52c360a98e9851a. 
I underestimated the strength of the framework's architecture ^^

**Comment by dwhitney** [comment]
My concerns were more practical than architectural - I'm using this in the
browser, so bundle size is a concern for me. It seemed to me that this
could be done with streams instead of iterators, which would free up that
dependency, and looking through the other dependencies it seems the only
one you really "need" is `sparqljs`. That said, I've only skimmed the
codebase so I could be off base. Either way I have been enjoying this
library!

D

**Comment by Callidon** [comment]
Well, not really, since Node.js streams are not native in browsers and require a polyfill. The main reason for using `asynciterator` is because it is much more easy to work with than Node.js streams.

**Comment by dwhitney** [comment]
I hear you on the polyfill, but I don't think they are easier. I had a hell
of a time making an iterator from a Promise (no docs on how to make your
own iterator), and I'm having problems that I suspect are related to my
implementation of the iterator, but I'm not quite sure... hopefully I
figure it out soon!

Have you had a look at funfix? https://github.com/funfix/funfix I've had a
lot of good experiences with it.

In any case - I think I should say that if you want to continue using
`asnynciterator` as a dependency, you can discard my idea of abstracting
the return type from `find` and `evalBGP` since it was mostly about
removing the dependency.

D

**Comment by Callidon** [comment]
Okay, thank you for the feedback. I will keep the changes to `Graph` API, because it is still a good idea from an architectural point of view. We will delay the discussion on the need for the `asynciterator` package for later ;-)

**Comment by dwhitney** [comment]
Hmm... I'm seeing some pretty significant slowdown in master now. Odd thing is it seems to only be happening in the browser and not in node. Here's a screenshot of some profiling I've been doing. I'll post more as I get more results
<img width="525" alt="screen shot 2018-10-02 at 11 41 21 pm" src="https://user-images.githubusercontent.com/33441/46388924-176d3c00-c69d-11e8-9efe-29a909af26e6.png">

**Comment by Callidon** [comment]
Ouch... I will just forward your comment to a new issue and we will continue the discussion here.

**Comment by Callidon** [comment]
Transferred to issue #6
