### ISSUE TITLE
Types Not Visible for Importing

### ISSUE THREAD

**Issue by thatcort** [Callidon/sparql-engine#30]
**Describe the bug**
I'm trying to use sparql-engine in a browser Angular Typescript app. When I try to implement Graph, the Algebra namespace is not visible for importing, resulting in all triples having type `any`.

The ExecutionContext and PIpelineInput types also require importing from deep within the sparql internals (e.g. 'sparql-engine/dist/engine/context/execution-context')

I have other questions about how to correctly implement Graph, that perhaps can be answered here as well:
- What is the correct use of ExecutionContext within the find method? Neither of the examples show its use.
- How do graphs within the execution context relate to the Graph subclass being implemented?

**To Reproduce**
1. Create an angular app: `npm i -g @angular/cli`, `ng new sparql-app`, `sparql-app`
2. Install sparql-engine and rdf-lib: `npm i --save sparql-engine rdflib`, `npm i --save-dev @types/rdflib`
3. Implement Graph (see attached source code)
[rdflib-graph.ts.txt](https://github.com/Callidon/sparql-engine/files/3567093/rdflib-graph.ts.txt)
4. See type errors

**Expected behavior**
All necessary types should be easily imported from the `sparql-engine` package.

**Desktop (please complete the following information):**
 - OS: Mac OSX 
 - Version: 0.5.1

**Comment by Callidon** [comment]
Hello

To answer to all your questions in order:

1) The `Algebra` type does not comes from the `sparql-engine` package, but from the [`sparqljs`](https://www.npmjs.com/package/sparqljs) package. As this package does not expose any Typescript types, we had to develop our own type mapping. **This is a known issue**, and we have planned to move to dedicated types that will be importable directly from the `sparql-engine` package. In the meantime, the custom types for `sparqljs` are available here [https://github.com/Callidon/sparql-engine/tree/master/types](https://github.com/Callidon/sparql-engine/tree/master/types).

2) For the ExecutionContext and PipelineInput types, this is a **new bug**. I will look into this, thank you for reporting it!

3) For the use of the ExecutionContext into the `find` method: You can think of the ExecutionContext as a big "all purposes" container that is shared across all the components of the query engine. It contains the graph currently selected, the custom functions declared, etc. In the `find` function, it does not have any purpose and you can safely ignore it. It is reserved for more advanced usage of the package, when you need very fine-grained control over query execution.

4) Again, graphs within the execution context are used in other parts of the package, mostly for the evaluation of the `GRAPH` and `SERVICE` clauses. In the scope of the `find` and `evalBGP` of the Graph class (its subclasses-, you can ignore it.

**Comment by Callidon** [comment]
I've just fixed the missing export for ExecutionContext and PipelineInput and released a new minor version (0.5.3) with the fixes.

**Comment by thatcort** [comment]
Thank you!

**Comment by vhf** [comment]
> 1. The `Algebra` type does not comes from the `sparql-engine` package, but from the [`sparqljs`](https://www.npmjs.com/package/sparqljs) package. As this package does not expose any Typescript types, we had to develop our own type mapping. **This is a known issue**, and we have planned to move to dedicated types that will be importable directly from the `sparql-engine` package. In the meantime, the custom types for `sparqljs` are available here https://github.com/Callidon/sparql-engine/tree/master/types.

(weighing in as another sparqljs user) I'm using these: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sparqljs/index.d.ts , `@types/sparqljs` on NPM

**Comment by Callidon** [comment]
> (weighing in as another sparqljs user) I'm using these: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sparqljs/index.d.ts , `@types/sparqljs` on NPM

Well, I've no idea that this one existed 🤣 It might be a good idea to swap to this declaration instead of our custom one, but I'm afraid of the headache I will get from changing ALL types declarations in the package...
