### ISSUE TITLE
BGP question

### ISSUE THREAD

**Issue by dwhitney** [Callidon/sparql-engine#4]
This is not really an issue but more of a question - some of the data sets I'm working with have time series data in them and basic queries to get date and value are suffering from the N + 1 select problem - date and value are related to an entity with a blank node, so I get a date and time query for each blank node which can be in the thousands. It's slow and I'm wondering if you have some suggestions for improving performance. My naive guess is that something different than the indexed nested loop join would be better but I'm new to this stuff and could use a pointer in the right direction

**Comment by Callidon** [comment]
I'm struggling to understand your issue. Do you have an example with a SPARQL query and some data to illustrate the issue?

**Comment by dwhitney** [comment]
I probably can't put anything together until Monday, but I think a sorted
merge join will solve my issue especially since the datasets are in sorted
order. I will post more if my experiments are successful
