### ISSUE TITLE
Add ability to sparql query over unbound (?g) named graphs

### ISSUE THREAD

**Issue by jbouecke** [Callidon/sparql-engine#44]
**Having variables that describes graph IRIs should be possible within a query**

A sparql query that should work according to the 1.1 spec is:

```sparql
  PREFIX dblp-pers: <https://dblp.org/pers/m/>
  PREFIX dblp-rdf: <https://dblp.uni-trier.de/rdf/schema-2017-04-18#>
  PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
  SELECT ?s ?name ?article ?g
  WHERE {
        GRAPH ?g {
          ?s rdf:type dblp-rdf:Person .
          ?s dblp-rdf:primaryFullPersonName ?name .
          ?s dblp-rdf:authorOf ?article .
      }
  }
``` 

I am also willing to contribute but have not much experience with this project yet. May be you can sketch a solution and point me to the important parts?

I created a test case for it that (of coarse) right now fails, and placed it into a pull request #43

**Comment by Callidon** [comment]
Hi,

Thank you for reporting this issue. I see exactly how to easily fix it, I will work on that as soon as possible and notify you when it's done.

**Comment by jbouecke** [comment]
Sounds wonderful.
Thanks! I did some research on javascript sparql engines and after that fix
it's for me by far the best!

Am Sa., 29. Feb. 2020 um 11:30 Uhr schrieb Thomas Minier <
notifications@github.com>:

**Comment by jbouecke** [comment]
Hi,
At first I want to thank you for your promt response last time!

But, even though it somehow improved, I am still not able to query the simple scenario described 
below.

**DataSet content**
* no content in the default (unnamed) graph
* 3 named graph with matching content each...

```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?g ?s ?o  WHERE
{
    GRAPH ?g
          {
            ?s rdf:type ?o .
          }
}
```

It would be fantastic if you can check that... I tried to dive into it by my selfe. However, it seems to call getNamedGraph(iri) with iri of type 'undefined' which seems to be _strange_. And even if I return the default graph, it is not working as expected.
