### ISSUE TITLE
Please use BGPCache type instead of LRUBGPCache

### ISSUE THREAD

**Issue by folkvir** [Callidon/sparql-engine#46]
https://github.com/Callidon/sparql-engine/blob/625c79d62b95230d8abdd0696a3d8a5f9698918b/src/engine/plan-builder.ts#L176

As noticed, use BGPCache instead of LRUBGPCache. We cant use a custom implementation based on BGPCache otherwise.

**Comment by Callidon** [comment]
Fixed in v0.7.3, it was a renaming glitch from VSCode...
