### ISSUE TITLE
Bug in levelgraph adapter (`this` not resolving as expected)

### ISSUE THREAD

**Issue by gavinpc-mindgrub** [Callidon/sparql-engine#60]
First, thanks for this *fantastic* project!  It is a thing of beauty.

**To Reproduce**
1. Use the levelgraph adapter (from the `examples` directory)
2. Do any update operation (the test program only does a read operation)

**Expected behavior**
Performs update operation

**Actual behavior**

```
TypeError: Cannot read property '_db' of undefined
```

**Additional context**

The reason for the error is that the `insert` and `delete` operations use `function` expressions in the Promise constructors, which changes the context of `this` resolution.

I am submitting a PR momentarily.

**Comment by Callidon** [comment]
Thank you for solving that, it been so long since we last tested the levelgraph adapter, it's no surprise to me that there are stills bugs in this example.
I've merged you pull request with the fix.
