### ISSUE TITLE
n3.js example errors with

### ISSUE THREAD

**Issue by kayakr** [Callidon/sparql-engine#7]
See n3.js example at https://runkit.com/kayakr/5bc6bbab5139200012a66294
Errors with "TypeError: Cannot set property 'iri' of undefined"
Using node v8.12.0
Can you assist?

**Comment by Callidon** [comment]
Hi,

Indeed, there is an error in the N3.js example: when creating a new HashMap dataset, yout need to provide the **default graph IRI** and the default graph instance.
```javascript
const graph = new N3Graph()
const dataset = new HashMapDataset('http://example.org#default', graph)
```
I've forked and fixed your runkit notebook here: [https://runkit.com/callidon/5bc6d8745139200012a69142](https://runkit.com/callidon/5bc6d8745139200012a69142).
I've also updated the example on the live repository.

By the way, with the new version developed on the [`push-rework`](https://github.com/Callidon/sparql-engine/tree/push-rework) branch, I will drop support for the `asynciterator` package. Thus, you will be able to simplify the implementation of `N3Graph.find` as this:
```javascript
find (triple) {
    const { subject, predicate, object } = formatTriplePattern(triple)
    return this._store.getTriples(subject, predicate, object)
  }
```
