### ISSUE TITLE
custom functions

### ISSUE THREAD

**Issue by dwhitney** [Callidon/sparql-engine#9]
**Is your feature request related to a problem? Please describe.**

I'd like to create a custom data type, similar to something like "xsd:date", and have a couple of functions available to filter on that custom type. 

For more detail - I have a lot of time series data describing some subject over time. Currently for each moment in time, I have a blank node to relate date and value. This is making the my queries slow because each blank node requires two bgp calls to get the date and value for each. I'd like to create a data type that smashes date and value together into one value and then I would not need the blank node, but I'd still need a way to filter on those values. I can use regular expressions, but I think that will be tough for my users. It would be nice to have a custom function to decouple those values like `BIND(timeseries:date(?timeseries) as ?date)` or `BIND(timeseries:value(?timeseries) as ?value)`.  I can do this with regular expressions, but I think that will become tedious.  

**Describe the solution you'd like**

Not sure. 

**Describe alternatives you've considered**

I can think of a way I could do this with regular expressions as described above, but I think that's not ideal if there is another way. I do See that Jena offers something like this https://github.com/apache/jena/blob/master/jena-arq/src-examples/arq/examples/propertyfunction/uppercase.java

**Comment by Callidon** [comment]
I've already think about that. It is not to hard to implement, but it will require a local fork of the SPARQL parser used in order to detect these custom functions.

I put this on my (endless) TODO list.

**Comment by dwhitney** [comment]
👍 for now I'm using regex but thanks for getting back to me

**Comment by Callidon** [comment]
solved in #13 and #14
